### ISSUE TITLE
FTBFS with GCC 16: the C++ standard is never declared, so a compiler default change breaks the build

### ISSUE THREAD

**Issue by Fantu** [mickem/nscp#1479]
`build.md` lists a "C++17 toolchain" as the requirement, but the build never tells CMake: there is no `CMAKE_CXX_STANDARD` (nor `target_compile_features`) anywhere, so the language level is whatever the compiler happens to default to.

Debian unstable now ships GCC 16 (`g++ 16.2.0`), whose default is `-std=gnu++20`, and 0.18.1 does not compile there:

```
modules/CauseCrashes/module.cpp:183:80: error: no matching function for call to
  'nscapi::plugin_instance_data<CauseCrashesModule>::plugin_instance_data(<brace-enclosed initializer list>)'
  183 |         static nscapi::plugin_instance_data<plugin_impl_class> plugin_instance{};
      |                                                                                ^
```

`plugin_instance_data` (`include/nscapi/nscapi_plugin_wrapper.hpp:27`) declares its copy constructor `= delete`. In C++17 the class is still an aggregate, so the `plugin_instance{}` line that `build/python/create_plugin_module.py` generates for **every** module is aggregate-initialised; in C++20 a user-declared constructor disqualifies the aggregate, and the deleted copy constructor left no default one to call. CauseCrashes is just the first module compiled.

This is not a 0.18.1 regression — the `= delete` dates back to `121587ff` (February) — and CI cannot see it: the Linux jobs build on Ubuntu 24.04 and Rocky, where the compiler still defaults to C++17.

Two things would help:

1. **Declare the standard** (`set(CMAKE_CXX_STANDARD 17)` + `CXX_STANDARD_REQUIRED`), so the language cannot move under the project every time a distribution bumps its compiler.
2. **Decide what is supported.** Is C++17 the floor, and is building as C++20 meant to work? Newer toolchains keep arriving — Debian unstable already, other distributions will follow — so it would help to know which compilers you want green, and perhaps to have one CI job on a rolling distribution catching this class of breakage early.

The minimal fix for this particular error is a defaulted constructor:

```c++
plugin_instance_data() = default;
```

**Comment by Fantu** [comment]
Working past this one turned up a second, independent failure with the same compiler. Posting it here rather than in a new issue since it is the same "does not build with GCC 16" story — happy to split it out if you prefer to track it separately.

Forcing `-std=gnu++17` gets the build to 93%, where both standalone clients fail to link:

```
undefined reference to `nscapi::plugin_singleton'
  from nrpe_client::client_handler::{log_debug,log_error,expand_path}
```

Those are the *module* handler's inline members, which log through `GET_CORE()`. `check_nrpe.cpp` and `check_nscp.cpp` use their own `stdout_client_handler` and never define the singleton — only `NSC_WRAP_DLL()` does, in plugins.

What makes GCC 16 emit them is speculative devirtualization. Building only `check_nscp_nrpe` from a clean tree:

| compiler | flags | result |
|---|---|---|
| g++ 16.2 | `-O2 -std=gnu++17` | undefined reference |
| g++ 16.2 | `-O2 -std=gnu++17 -fno-devirtualize` | links |
| g++ 16.2 | `-O0 -std=gnu++17` | links |
| g++ 15.3 | `-O2` (C++17 default) | links |

Same result on 0.14.1, so the symbol was always missing: older GCC simply never emitted the functions that reference it.

The fix is what the unit-test binaries already do, and what `CLAUDE.md` documents for them:

```c++
nscapi::helper_singleton *nscapi::plugin_singleton = new nscapi::helper_singleton();
```

I have not yet built with both fixes applied, so I cannot say whether anything further in the tree is unhappy with GCC 16. (I'll try now)

**Comment by mickem** [comment]
Hmm, on windows we build using v141-xp which is somewhere in-between vc++14 and vc++17 so "full" vc17 is "not required" but likely some features of it.

That said we should definitely define this to "what we want to use" instead of whatever happens to be there...

And we should definitely ensure that it works on newer compilers as well...  I will look into it...

Thanks...

**Comment by mickem** [comment]
I have review this now and understand the problem so I suggest adding the set for declaring the standard to 17, so feel free to do that in the PR you have open and we can get them both in one go.

**Comment by mickem** [comment]
thanks... closing as this was merged...
